name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Say hello
        run: |
          echo "Hello World!"

      - name: Print current time and date
        run: |
          echo "Current date and time: $(date +'%Y-%m-%d %H:%M:%S')"

      - name: List directory contents
        run: |
          ls -l