name: CI Metrics Collection

on:
    workflow_run:
        workflows: ['CI/CD Deployment Pipeline']
        types: [completed]

jobs:
    collect-metrics:
        runs-on: ubuntu-latest
        steps:
            - name: Get workflow metrics
              id: metrics
              uses: actions/github-script@v6
              with:
                  script: |
                      const run = await github.rest.actions.getWorkflowRun({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        run_id: context.payload.workflow_run.id
                      });

                      const duration = Math.round(
                        (new Date(run.data.updated_at) - 
                        new Date(run.data.run_started_at)) / 1000;

                      return {
                        duration: duration,
                        conclusion: run.data.conclusion,
                        workflow: run.data.name
                      };

            - name: Store metrics
              run: |
                  echo "Collected metrics:"
                  echo "Duration: ${{ steps.metrics.outputs.duration }}s"
                  echo "Status: ${{ steps.metrics.outputs.conclusion }}"
                  echo "Workflow: ${{ steps.metrics.outputs.workflow }}"
              # Replace with actual metrics service integration
